# Generated by Django 2.0.1 on 2019-11-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180506_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100),
        ),
    ]
