# Generated by Django 2.2.10 on 2020-11-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200308_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=64)),
                ('album', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('dataURL', models.URLField()),
            ],
        ),
    ]
