# Generated by Django 2.2.10 on 2021-08-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210812_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='blog/static/blog/featured_image/%Y/%m/%d/'),
        ),
    ]
