# Generated by Django 2.2.10 on 2021-08-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210812_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_image/%Y/%m/%d/'),
        ),
    ]
